from https://www.bls.gov/iag/tgs/iag_index_naics.htm

goods-producing industries

natural resources and mining
agriculture, forestry, fishing and hunting (naics 11)
crop production (naics 111)
animal production (naics 112)
forestry and logging (naics 113)
fishing, hunting and trapping (naics 114)
support activities for agriculture and forestry (naics 115)
mining, quarrying, and oil and gas extraction (naics 21)
oil and gas extraction (naics 211)
mining (except oil and gas) (naics 212)
support activities for mining (naics 213)
construction
construction (naics 23)
construction of buildings (naics 236)
heavy and civil engineering construction (naics 237)
specialty trade contractors (naics 238)
manufacturing
manufacturing (naics 31-33)
food manufacturing (naics 311)
beverage and tobacco product manufacturing (naics 312)
textile mills (naics 313)
textile product mills (naics 314)
apparel manufacturing (naics 315)
leather and allied product manufacturing (naics 316)
wood product manufacturing (naics 321)
paper manufacturing (naics 322)
printing and related support activities (naics 323)
petroleum and coal products manufacturing (naics 324)
chemical manufacturing (naics 325)
plastics and rubber products manufacturing (naics 326)
nonmetallic mineral product manufacturing (naics 327)
primary metal manufacturing (naics 331)
fabricated metal product manufacturing (naics 332)
machinery manufacturing (naics 333)
computer and electronic product manufacturing (naics 334)
electrical equipment, appliance, and component manufacturing (naics 335)
transportation equipment manufacturing (naics 336)
furniture and related product manufacturing (naics 337)
miscellaneous manufacturing (naics 339)
service-providing industries

trade, transportation, and utilities
wholesale trade (naics 42)
merchant wholesalers, durable goods (naics 423)
merchant wholesalers, nondurable goods (naics 424)
wholesale electronic markets and agents and brokers (naics 425)
retail trade (naics 44-45)
motor vehicle and parts dealers (naics 441)
furniture and home furnishings stores (naics 442)
electronics and appliance stores (naics 443)
building material and garden equipment and supplies dealers (naics 444)
food and beverage stores (naics 445)
health and personal care stores (naics 446)
gasoline stations (naics 447)
clothing and clothing accessories stores (naics 448)
sporting goods, hobby, book, and music stores (naics 451)
general merchandise stores (naics 452)
miscellaneous store retailers (naics 453)
nonstore retailers (naics 454)
transportation and warehousing (naics 48-49)
air transportation (naics 481)
rail transportation (naics 482)
water transportation (naics 483)
truck transportation (naics 484)
transit and ground passenger transportation (naics 485)
pipeline transportation (naics 486)
scenic and sightseeing transportation (naics 487)
support activities for transportation (naics 488)
postal service (naics 491)
couriers and messengers (naics 492)
warehousing and storage (naics 493)
utilities (naics 22)
information
information (naics 51)
publishing industries (except internet) (naics 511)
motion picture and sound recording industries (naics 512)
broadcasting (except internet) (naics 515)
internet publishing and broadcasting (naics 516)
telecommunications (naics 517)
data processing, hosting, and related services (naics 518)
other information services (naics 519)
financial activities
finance and insurance (naics 52)
monetary authorities - central bank (naics 521)
credit intermediation and related activities (naics 522)
securities, commodity contracts, and other financial investments and related activities (naics 523)
insurance carriers and related activities (naics 524)
funds, trusts, and other financial vehicles (naics 525)
real estate and rental and leasing (naics 53)
real estate (naics 531)
rental and leasing services (naics 532)
lessors of nonfinancial intangible assets (except copyrighted works) (naics 533)
professional and business services
professional, scientific, and technical services (naics 54)
management of companies and enterprises (naics 55)
administrative and support and waste management and remediation services (naics 56)
administrative and support services (naics 561)
waste management and remediation services (naics 562)
education and health services
educational services (naics 61)
health care and social assistance (naics 62)
ambulatory health care services (naics 621)
hospitals (naics 622)
nursing and residential care facilities (naics 623)
social assistance (naics 624)
leisure and hospitality
arts, entertainment, and recreation (naics 71)
performing arts, spectator sports, and related industries (naics 711)
museums, historical sites, and similar institutions (naics 712)
amusement, gambling, and recreation industries (naics 713)
accommodation and food services (naics 72)
accommodation (naics 721)
food services and drinking places (naics 722)
other services (except public administration)
other services (except public administration) (naics 81)
repair and maintenance (naics 811)
personal and laundry services (naics 812)
religious, grantmaking, civic, professional, and similar organizations (naics 813)
private households (naics 814)
